Fix type checking of `__in` lookup (#3314)
The base type was being used instead of expecting an iterable, leading
to errors such as:

```
error: Incompatible type for lookup 'month__in': (got "list[int]", expected "int")  [misc]
```

This fixes for lookups on both standard fields and annotations.